pre-release-replacements = [
  {file="../README.md", search="adze = .*", replace="adze = \"{{version}}\""},
  {file="../README.md", search="adze-tool = .*", replace="adze-tool = \"{{version}}\""},
]

consolidate-commits = true
shared-version = true
