//! Combined policy report — the single human-facing summary.

use anyhow::{Context, Result};
use std::fs;

use super::{ensure_reports_dir, file_policy, lint_policy, no_panic, workspace_root};

#[derive(Debug, Default, Clone)]
pub struct RunOpts {
    pub strict: bool,
}

pub fn run(opts: RunOpts) -> Result<()> {
    let root = workspace_root()?;
    let reports_dir = ensure_reports_dir(&root)?;

    let no_panic_outcome = no_panic::run(no_panic::RunOpts {
        strict: false,
        propose: false,
    })?;
    let file_outcome = file_policy::run(file_policy::RunOpts { strict: false })?;
    let lint_outcome = lint_policy::run(lint_policy::RunOpts { strict: false })?;

    let summary_path = reports_dir.join("policy-summary.md");
    let mut s = String::new();
    s.push_str("# Adze policy summary\n\n");
    s.push_str("| Surface       | Findings | Report                              |\n");
    s.push_str("| ------------- | -------: | ----------------------------------- |\n");
    s.push_str(&format!(
        "| no-panic      | {:>8} | `{}` |\n",
        no_panic_outcome.findings,
        rel(&no_panic_outcome.report_md, &root)
    ));
    s.push_str(&format!(
        "| file-policy   | {:>8} | `{}` |\n",
        file_outcome.findings,
        rel(&file_outcome.report_md, &root)
    ));
    s.push_str(&format!(
        "| lint-policy   | {:>8} | `{}` |\n",
        lint_outcome.findings,
        rel(&lint_outcome.report_md, &root)
    ));
    s.push_str("\nGenerated by `cargo xtask policy-report`. See `docs/policy/` for the policy.\n");
    fs::write(&summary_path, s).with_context(|| format!("write {}", summary_path.display()))?;

    eprintln!("[policy] summary written to {}", summary_path.display());

    let total = no_panic_outcome.findings + file_outcome.findings + lint_outcome.findings;
    if opts.strict && total > 0 {
        anyhow::bail!("policy: {} total findings", total);
    }
    Ok(())
}

fn rel(p: &std::path::Path, root: &std::path::Path) -> String {
    p.strip_prefix(root)
        .unwrap_or(p)
        .to_string_lossy()
        .replace('\\', "/")
}
