#![allow(clippy::needless_range_loop)]

//! Comprehensive tests for `BuildStats` generated by adze-tool.
//!
//! Covers: direct construction, Debug formatting, stats from the build
//! pipeline, grammar-complexity correlation, conflict counting, comparison
//! between grammars, zero-complexity grammars, and large grammars.

use std::fs;

use adze_ir::{
    Associativity, Grammar, PrecedenceKind, ProductionId, Rule, Symbol, SymbolId, Token,
    TokenPattern,
};
use adze_tool::pure_rust_builder::{BuildOptions, BuildResult, BuildStats, build_parser};
use tempfile::TempDir;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Build options writing into a fresh temp directory.
fn temp_opts() -> (TempDir, BuildOptions) {
    let dir = TempDir::new().unwrap();
    let opts = BuildOptions {
        out_dir: dir.path().to_string_lossy().into(),
        emit_artifacts: false,
        compress_tables: false,
    };
    (dir, opts)
}

/// Minimal grammar: one token, one non-terminal with a single production.
fn minimal_grammar(name: &str) -> Grammar {
    let mut g = Grammar::new(name.to_string());
    let tok = SymbolId(1);
    let src = SymbolId(2);
    g.tokens.insert(
        tok,
        Token {
            name: "number".into(),
            pattern: TokenPattern::Regex(r"\d+".into()),
            fragile: false,
        },
    );
    g.rule_names.insert(src, "source_file".into());
    g.rules.entry(src).or_default().push(Rule {
        lhs: src,
        rhs: vec![Symbol::Terminal(tok)],
        precedence: None,
        associativity: None,
        fields: vec![],
        production_id: ProductionId(0),
    });
    g
}

/// Build a grammar and return the BuildResult.
fn build(g: Grammar) -> BuildResult {
    let (_dir, opts) = temp_opts();
    build_parser(g, opts).expect("build should succeed")
}

/// Build a grammar and return just the stats.
fn stats_for(g: Grammar) -> BuildStats {
    build(g).build_stats
}

/// Build grammar.js through the pure-Rust builder and return the result.
fn build_js(js: &str) -> BuildResult {
    let dir = TempDir::new().unwrap();
    let path = dir.path().join("grammar.js");
    fs::write(&path, js).unwrap();
    let opts = BuildOptions {
        out_dir: dir.path().to_string_lossy().into(),
        emit_artifacts: false,
        compress_tables: false,
    };
    adze_tool::pure_rust_builder::build_parser_from_grammar_js(&path, opts).unwrap()
}

// =========================================================================
// 1. BuildStats direct construction
// =========================================================================

#[test]
fn direct_construction_zero_values() {
    let s = BuildStats {
        state_count: 0,
        symbol_count: 0,
        conflict_cells: 0,
    };
    assert_eq!(s.state_count, 0);
    assert_eq!(s.symbol_count, 0);
    assert_eq!(s.conflict_cells, 0);
}

#[test]
fn direct_construction_nonzero_values() {
    let s = BuildStats {
        state_count: 42,
        symbol_count: 10,
        conflict_cells: 3,
    };
    assert_eq!(s.state_count, 42);
    assert_eq!(s.symbol_count, 10);
    assert_eq!(s.conflict_cells, 3);
}

#[test]
fn direct_construction_large_values() {
    let s = BuildStats {
        state_count: 100_000,
        symbol_count: 50_000,
        conflict_cells: 25_000,
    };
    assert_eq!(s.state_count, 100_000);
    assert_eq!(s.symbol_count, 50_000);
    assert_eq!(s.conflict_cells, 25_000);
}

// =========================================================================
// 2. Debug formatting
// =========================================================================

#[test]
fn debug_format_contains_field_names() {
    let s = BuildStats {
        state_count: 5,
        symbol_count: 3,
        conflict_cells: 1,
    };
    let dbg = format!("{:?}", s);
    assert!(dbg.contains("state_count"));
    assert!(dbg.contains("symbol_count"));
    assert!(dbg.contains("conflict_cells"));
}

#[test]
fn debug_format_contains_values() {
    let s = BuildStats {
        state_count: 7,
        symbol_count: 4,
        conflict_cells: 2,
    };
    let dbg = format!("{:?}", s);
    assert!(dbg.contains("7"), "debug should contain state_count value");
    assert!(dbg.contains("4"), "debug should contain symbol_count value");
    assert!(
        dbg.contains("2"),
        "debug should contain conflict_cells value"
    );
}

#[test]
fn debug_format_zero_stats() {
    let s = BuildStats {
        state_count: 0,
        symbol_count: 0,
        conflict_cells: 0,
    };
    let dbg = format!("{:?}", s);
    assert!(!dbg.is_empty());
    // All zeros should still print the struct name
    assert!(dbg.contains("BuildStats"));
}

// =========================================================================
// 3. Stats from a real build — minimal grammar
// =========================================================================

#[test]
fn minimal_grammar_produces_nonzero_state_count() {
    let s = stats_for(minimal_grammar("min_state"));
    assert!(
        s.state_count > 0,
        "even a trivial grammar needs at least one state"
    );
}

#[test]
fn minimal_grammar_produces_nonzero_symbol_count() {
    let s = stats_for(minimal_grammar("min_sym"));
    assert!(
        s.symbol_count > 0,
        "symbol count should include at least the token and the non-terminal"
    );
}

#[test]
fn minimal_grammar_conflict_cells_are_small() {
    let s = stats_for(minimal_grammar("min_conflict"));
    // A trivial grammar should have very few (possibly zero) conflicts.
    assert!(
        s.conflict_cells <= 2,
        "minimal grammar should have at most 2 conflict cells, got {}",
        s.conflict_cells
    );
}

// =========================================================================
// 4. Symbol count includes terminals and non-terminals
// =========================================================================

#[test]
fn symbol_count_grows_with_tokens() {
    let s1 = stats_for(minimal_grammar("sym1"));

    // Build a grammar with an extra token
    let mut g = minimal_grammar("sym2");
    let extra_tok = SymbolId(10);
    g.tokens.insert(
        extra_tok,
        Token {
            name: "ident".into(),
            pattern: TokenPattern::Regex(r"[a-z]+".into()),
            fragile: false,
        },
    );
    // Add a rule using the new token so it's reachable
    let src = SymbolId(2);
    g.rules.entry(src).or_default().push(Rule {
        lhs: src,
        rhs: vec![Symbol::Terminal(extra_tok)],
        precedence: None,
        associativity: None,
        fields: vec![],
        production_id: ProductionId(1),
    });
    let s2 = stats_for(g);

    assert!(
        s2.symbol_count >= s1.symbol_count,
        "more tokens should yield at least as many symbols: {} vs {}",
        s2.symbol_count,
        s1.symbol_count,
    );
}

#[test]
fn symbol_count_grows_with_nonterminals() {
    let s1 = stats_for(minimal_grammar("nt1"));

    let mut g = minimal_grammar("nt2");
    let extra_nt = SymbolId(20);
    let tok = SymbolId(1);
    g.rule_names.insert(extra_nt, "extra_rule".into());
    g.rules.entry(extra_nt).or_default().push(Rule {
        lhs: extra_nt,
        rhs: vec![Symbol::Terminal(tok)],
        precedence: None,
        associativity: None,
        fields: vec![],
        production_id: ProductionId(10),
    });
    // Wire extra_nt into source_file so it is reachable
    let src = SymbolId(2);
    g.rules.entry(src).or_default().push(Rule {
        lhs: src,
        rhs: vec![Symbol::NonTerminal(extra_nt)],
        precedence: None,
        associativity: None,
        fields: vec![],
        production_id: ProductionId(11),
    });
    let s2 = stats_for(g);

    assert!(
        s2.symbol_count >= s1.symbol_count,
        "extra non-terminal should not shrink symbol count: {} vs {}",
        s2.symbol_count,
        s1.symbol_count,
    );
}

// =========================================================================
// 5. State count correlates with grammar size
// =========================================================================

#[test]
fn more_rules_yield_at_least_as_many_states() {
    let s_small = stats_for(minimal_grammar("st_small"));

    let mut g = minimal_grammar("st_big");
    let extra_tok = SymbolId(30);
    g.tokens.insert(
        extra_tok,
        Token {
            name: "ident".into(),
            pattern: TokenPattern::Regex(r"[a-z]+".into()),
            fragile: false,
        },
    );
    let src = SymbolId(2);
    g.rules.entry(src).or_default().push(Rule {
        lhs: src,
        rhs: vec![Symbol::Terminal(extra_tok)],
        precedence: None,
        associativity: None,
        fields: vec![],
        production_id: ProductionId(5),
    });
    let s_big = stats_for(g);

    assert!(
        s_big.state_count >= s_small.state_count,
        "bigger grammar should not have fewer states: {} vs {}",
        s_big.state_count,
        s_small.state_count,
    );
}

// =========================================================================
// 6. Conflict cell counting
// =========================================================================

#[test]
fn ambiguous_grammar_has_conflicts() {
    // expr -> expr "+" expr  (left-recursive, ambiguous without precedence)
    let mut g = Grammar::new("ambig".to_string());
    let num = SymbolId(1);
    let plus = SymbolId(3);
    let expr = SymbolId(4);

    g.tokens.insert(
        num,
        Token {
            name: "number".into(),
            pattern: TokenPattern::Regex(r"\d+".into()),
            fragile: false,
        },
    );
    g.tokens.insert(
        plus,
        Token {
            name: "plus".into(),
            pattern: TokenPattern::String("+".into()),
            fragile: false,
        },
    );
    g.rule_names.insert(expr, "source_file".into());

    // expr -> number
    g.rules.entry(expr).or_default().push(Rule {
        lhs: expr,
        rhs: vec![Symbol::Terminal(num)],
        precedence: None,
        associativity: None,
        fields: vec![],
        production_id: ProductionId(0),
    });
    // expr -> expr + expr  (intentionally ambiguous)
    g.rules.entry(expr).or_default().push(Rule {
        lhs: expr,
        rhs: vec![
            Symbol::NonTerminal(expr),
            Symbol::Terminal(plus),
            Symbol::NonTerminal(expr),
        ],
        precedence: None,
        associativity: None,
        fields: vec![],
        production_id: ProductionId(1),
    });

    let s = stats_for(g);
    // GLR builder should detect the shift/reduce ambiguity
    assert!(
        s.conflict_cells > 0,
        "ambiguous grammar without precedence should have conflict cells, got {}",
        s.conflict_cells,
    );
}

#[test]
fn unambiguous_grammar_has_few_conflicts() {
    let s = stats_for(minimal_grammar("unamb"));
    assert!(
        s.conflict_cells <= 2,
        "unambiguous grammar should have at most 2 conflict cells, got {}",
        s.conflict_cells,
    );
}

#[test]
fn precedence_can_reduce_conflicts() {
    // Build two grammars: one with precedence, one without
    let make = |name: &str, prec: bool| -> Grammar {
        let mut g = Grammar::new(name.to_string());
        let num = SymbolId(1);
        let plus = SymbolId(3);
        let expr = SymbolId(4);

        g.tokens.insert(
            num,
            Token {
                name: "number".into(),
                pattern: TokenPattern::Regex(r"\d+".into()),
                fragile: false,
            },
        );
        g.tokens.insert(
            plus,
            Token {
                name: "plus".into(),
                pattern: TokenPattern::String("+".into()),
                fragile: false,
            },
        );
        g.rule_names.insert(expr, "source_file".into());
        g.rules.entry(expr).or_default().push(Rule {
            lhs: expr,
            rhs: vec![Symbol::Terminal(num)],
            precedence: None,
            associativity: None,
            fields: vec![],
            production_id: ProductionId(0),
        });
        g.rules.entry(expr).or_default().push(Rule {
            lhs: expr,
            rhs: vec![
                Symbol::NonTerminal(expr),
                Symbol::Terminal(plus),
                Symbol::NonTerminal(expr),
            ],
            precedence: if prec {
                Some(PrecedenceKind::Static(1))
            } else {
                None
            },
            associativity: if prec {
                Some(Associativity::Left)
            } else {
                None
            },
            fields: vec![],
            production_id: ProductionId(1),
        });
        g
    };

    let s_prec = stats_for(make("prec_yes", true));
    let s_noprec = stats_for(make("prec_no", false));

    // With precedence the builder may still keep Fork actions, but
    // conflict_cells should be <= the unresolved case.
    assert!(
        s_prec.conflict_cells <= s_noprec.conflict_cells,
        "precedence should not increase conflicts: with={} without={}",
        s_prec.conflict_cells,
        s_noprec.conflict_cells,
    );
}

// =========================================================================
// 7. Stats comparison between grammars
// =========================================================================

#[test]
fn sample_grammar_has_more_symbols_than_minimal() {
    let s_min = stats_for(minimal_grammar("cmp_min"));
    let s_sample = stats_for(adze_tool::GrammarConverter::create_sample_grammar());

    assert!(
        s_sample.symbol_count >= s_min.symbol_count,
        "sample grammar should have at least as many symbols as minimal: {} vs {}",
        s_sample.symbol_count,
        s_min.symbol_count,
    );
}

#[test]
fn sample_grammar_has_more_states_than_minimal() {
    let s_min = stats_for(minimal_grammar("cmp_min2"));
    let s_sample = stats_for(adze_tool::GrammarConverter::create_sample_grammar());

    assert!(
        s_sample.state_count >= s_min.state_count,
        "sample grammar should have at least as many states as minimal: {} vs {}",
        s_sample.state_count,
        s_min.state_count,
    );
}

#[test]
fn different_grammar_names_do_not_affect_stats_shape() {
    let s1 = stats_for(minimal_grammar("name_a"));
    let s2 = stats_for(minimal_grammar("name_b"));
    assert_eq!(s1.state_count, s2.state_count);
    assert_eq!(s1.symbol_count, s2.symbol_count);
    assert_eq!(s1.conflict_cells, s2.conflict_cells);
}

// =========================================================================
// 8. Zero-complexity / degenerate grammars
// =========================================================================

#[test]
fn single_token_grammar_state_count() {
    let s = stats_for(minimal_grammar("single_tok"));
    // At minimum: initial state + accepting state
    assert!(
        s.state_count >= 2,
        "even a single-token grammar should have >= 2 states, got {}",
        s.state_count,
    );
}

#[test]
fn single_token_grammar_symbol_count_includes_eof() {
    let s = stats_for(minimal_grammar("eof_sym"));
    // 1 token + 1 non-terminal + EOF + augmented start = at least 3 symbols
    assert!(
        s.symbol_count >= 3,
        "single token grammar should have >= 3 symbols (tok + nt + eof), got {}",
        s.symbol_count,
    );
}

// =========================================================================
// 9. Large grammar stats (via grammar.js)
// =========================================================================

#[test]
fn large_grammar_has_many_states() {
    let mut rules = String::from("source: $ => choice(\n");
    for i in 0..20 {
        if i > 0 {
            rules.push_str(",\n");
        }
        rules.push_str(&format!("      $.r_{i}"));
    }
    rules.push_str("\n    )");
    for i in 0..20 {
        rules.push_str(&format!(",\n    r_{i}: $ => /tok{i}/"));
    }
    let js = format!("module.exports = grammar({{ name: 'big', rules: {{ {rules} }} }});");
    let r = build_js(&js);
    assert!(
        r.build_stats.state_count > 2,
        "large grammar should have more than 2 states, got {}",
        r.build_stats.state_count,
    );
}

#[test]
fn large_grammar_has_many_symbols() {
    let mut rules = String::from("source: $ => choice(\n");
    for i in 0..20 {
        if i > 0 {
            rules.push_str(",\n");
        }
        rules.push_str(&format!("      $.r_{i}"));
    }
    rules.push_str("\n    )");
    for i in 0..20 {
        rules.push_str(&format!(",\n    r_{i}: $ => /tok{i}/"));
    }
    let js = format!("module.exports = grammar({{ name: 'bigsym', rules: {{ {rules} }} }});");
    let r = build_js(&js);
    // 20 tokens + 21 non-terminals (source + r_0..r_19) + EOF
    assert!(
        r.build_stats.symbol_count >= 20,
        "large grammar should have >= 20 symbols, got {}",
        r.build_stats.symbol_count,
    );
}

#[test]
fn large_grammar_scales_relative_to_small() {
    let s_small = stats_for(minimal_grammar("scale_sm"));

    let mut rules = String::from("source: $ => choice(\n");
    for i in 0..15 {
        if i > 0 {
            rules.push_str(",\n");
        }
        rules.push_str(&format!("      $.r_{i}"));
    }
    rules.push_str("\n    )");
    for i in 0..15 {
        rules.push_str(&format!(",\n    r_{i}: $ => /tok{i}/"));
    }
    let js = format!("module.exports = grammar({{ name: 'scale_lg', rules: {{ {rules} }} }});");
    let r_large = build_js(&js);

    assert!(
        r_large.build_stats.symbol_count > s_small.symbol_count,
        "large grammar should have strictly more symbols than minimal"
    );
    assert!(
        r_large.build_stats.state_count > s_small.state_count,
        "large grammar should have strictly more states than minimal"
    );
}

// =========================================================================
// 10. Integration: BuildResult carries coherent stats
// =========================================================================

#[test]
fn build_result_has_nonempty_grammar_name() {
    let r = build(minimal_grammar("named"));
    assert_eq!(r.grammar_name, "named");
}

#[test]
fn build_result_stats_are_accessible() {
    let r = build(minimal_grammar("access"));
    // Just ensure all fields are readable without panic
    let _ = r.build_stats.state_count;
    let _ = r.build_stats.symbol_count;
    let _ = r.build_stats.conflict_cells;
}

#[test]
fn build_result_parser_code_is_nonempty() {
    let r = build(minimal_grammar("code"));
    assert!(!r.parser_code.is_empty());
}

#[test]
fn build_result_node_types_json_is_nonempty() {
    let r = build(minimal_grammar("ntj"));
    assert!(!r.node_types_json.is_empty());
}

// =========================================================================
// 11. Stats with compression vs without
// =========================================================================

#[test]
fn compressed_and_uncompressed_yield_same_stats() {
    let g1 = minimal_grammar("comp_on");
    let g2 = minimal_grammar("comp_off");

    let dir1 = TempDir::new().unwrap();
    let opts1 = BuildOptions {
        out_dir: dir1.path().to_string_lossy().into(),
        emit_artifacts: false,
        compress_tables: true,
    };
    let r1 = build_parser(g1, opts1).unwrap();

    let dir2 = TempDir::new().unwrap();
    let opts2 = BuildOptions {
        out_dir: dir2.path().to_string_lossy().into(),
        emit_artifacts: false,
        compress_tables: false,
    };
    let r2 = build_parser(g2, opts2).unwrap();

    // Stats come from the parse table before compression, so they should match
    assert_eq!(r1.build_stats.state_count, r2.build_stats.state_count);
    assert_eq!(r1.build_stats.symbol_count, r2.build_stats.symbol_count);
    assert_eq!(r1.build_stats.conflict_cells, r2.build_stats.conflict_cells);
}

// =========================================================================
// 12. Multiple-alternative grammar stats
// =========================================================================

#[test]
fn grammar_with_many_alternatives() {
    let mut g = Grammar::new("multi_alt".to_string());
    let src = SymbolId(100);
    g.rule_names.insert(src, "source_file".into());

    for i in 0..10 {
        let tok_id = SymbolId(i + 1);
        g.tokens.insert(
            tok_id,
            Token {
                name: format!("tok_{i}"),
                pattern: TokenPattern::Regex(format!("t{i}")),
                fragile: false,
            },
        );
        g.rules.entry(src).or_default().push(Rule {
            lhs: src,
            rhs: vec![Symbol::Terminal(tok_id)],
            precedence: None,
            associativity: None,
            fields: vec![],
            production_id: ProductionId(i as u16),
        });
    }

    let s = stats_for(g);
    // 10 tokens + at least source_file + EOF
    assert!(
        s.symbol_count >= 12,
        "10-alternative grammar should have >= 12 symbols, got {}",
        s.symbol_count,
    );
    assert!(s.state_count > 0);
}

// =========================================================================
// 13. Grammar with chained non-terminals
// =========================================================================

#[test]
fn chained_nonterminals_increase_state_count() {
    // A -> B, B -> C, C -> tok
    let mut g = Grammar::new("chain".to_string());
    let tok = SymbolId(1);
    let a = SymbolId(10);
    let b = SymbolId(11);
    let c = SymbolId(12);

    g.tokens.insert(
        tok,
        Token {
            name: "x".into(),
            pattern: TokenPattern::String("x".into()),
            fragile: false,
        },
    );
    g.rule_names.insert(a, "source_file".into());
    g.rule_names.insert(b, "b".into());
    g.rule_names.insert(c, "c".into());

    g.rules.entry(a).or_default().push(Rule {
        lhs: a,
        rhs: vec![Symbol::NonTerminal(b)],
        precedence: None,
        associativity: None,
        fields: vec![],
        production_id: ProductionId(0),
    });
    g.rules.entry(b).or_default().push(Rule {
        lhs: b,
        rhs: vec![Symbol::NonTerminal(c)],
        precedence: None,
        associativity: None,
        fields: vec![],
        production_id: ProductionId(1),
    });
    g.rules.entry(c).or_default().push(Rule {
        lhs: c,
        rhs: vec![Symbol::Terminal(tok)],
        precedence: None,
        associativity: None,
        fields: vec![],
        production_id: ProductionId(2),
    });

    let s_chain = stats_for(g);
    let s_min = stats_for(minimal_grammar("chain_base"));

    assert!(
        s_chain.state_count >= s_min.state_count,
        "chained grammar should have at least as many states: {} vs {}",
        s_chain.state_count,
        s_min.state_count,
    );
    // Chain adds 2 extra non-terminals
    assert!(
        s_chain.symbol_count >= s_min.symbol_count,
        "chained grammar should have more symbols: {} vs {}",
        s_chain.symbol_count,
        s_min.symbol_count,
    );
}
