// End-to-end test of the pure-Rust Tree-sitter runtime
// This tests the complete pipeline from grammar to parsing

use rust_sitter::lexer::GrammarLexer;
use rust_sitter::parser::Parser;
use rust_sitter_glr_core::{Action, ParseTable, SymbolMetadata};
use rust_sitter_ir::{
    Grammar, ProductionId, Rule, RuleId, StateId, Symbol, SymbolId, Token as IrToken, TokenPattern,
};

/// Create a simple arithmetic grammar for testing
fn create_arithmetic_grammar() -> Grammar {
    let mut grammar = Grammar::new("arithmetic".to_string());

    // Tokens
    // 0 = EOF (implicit)
    // 1 = number
    // 2 = +
    // 3 = -
    // 4 = *
    // 5 = (
    // 6 = )
    // 7 = whitespace (skip)

    grammar.tokens.insert(
        SymbolId(1),
        IrToken {
            name: "number".to_string(),
            fragile: false,
            pattern: TokenPattern::Regex(r"\d+".to_string()),
        },
    );

    grammar.tokens.insert(
        SymbolId(2),
        IrToken {
            name: "plus".to_string(),
            fragile: false,
            pattern: TokenPattern::String("+".to_string()),
        },
    );

    grammar.tokens.insert(
        SymbolId(3),
        IrToken {
            name: "minus".to_string(),
            fragile: false,
            pattern: TokenPattern::String("-".to_string()),
        },
    );

    grammar.tokens.insert(
        SymbolId(4),
        IrToken {
            name: "star".to_string(),
            fragile: false,
            pattern: TokenPattern::String("*".to_string()),
        },
    );

    grammar.tokens.insert(
        SymbolId(5),
        IrToken {
            name: "lparen".to_string(),
            fragile: false,
            pattern: TokenPattern::String("(".to_string()),
        },
    );

    grammar.tokens.insert(
        SymbolId(6),
        IrToken {
            name: "rparen".to_string(),
            fragile: false,
            pattern: TokenPattern::String(")".to_string()),
        },
    );

    grammar.tokens.insert(
        SymbolId(7),
        IrToken {
            name: "whitespace".to_string(),
            fragile: false,
            pattern: TokenPattern::Regex(r"\s+".to_string()),
        },
    );

    // Non-terminals
    // 10 = expression
    // 11 = term
    // 12 = factor

    // Rules:
    // expression -> expression + term (rule 100)
    // expression -> expression - term (rule 101)
    // expression -> term (rule 102)
    // term -> term * factor (rule 110)
    // term -> factor (rule 111)
    // factor -> ( expression ) (rule 120)
    // factor -> number (rule 121)

    grammar
        .rules
        .entry(SymbolId(100))
        .or_insert_with(Vec::new)
        .push(Rule {
            lhs: SymbolId(10), // expression
            rhs: vec![
                Symbol::NonTerminal(SymbolId(10)), // expression
                Symbol::Terminal(SymbolId(2)),     // +
                Symbol::NonTerminal(SymbolId(11)), // term
            ],
            precedence: None,
            associativity: None,
            production_id: ProductionId(0),
            fields: Default::default(),
        });

    grammar
        .rules
        .entry(SymbolId(102))
        .or_insert_with(Vec::new)
        .push(Rule {
            lhs: SymbolId(10),                            // expression
            rhs: vec![Symbol::NonTerminal(SymbolId(11))], // term
            precedence: None,
            associativity: None,
            production_id: ProductionId(0),
            fields: Default::default(),
        });

    grammar
        .rules
        .entry(SymbolId(111))
        .or_insert_with(Vec::new)
        .push(Rule {
            lhs: SymbolId(11),                            // term
            rhs: vec![Symbol::NonTerminal(SymbolId(12))], // factor
            precedence: None,
            associativity: None,
            production_id: ProductionId(0),
            fields: Default::default(),
        });

    grammar
        .rules
        .entry(SymbolId(121))
        .or_insert_with(Vec::new)
        .push(Rule {
            lhs: SymbolId(12),                        // factor
            rhs: vec![Symbol::Terminal(SymbolId(1))], // number
            precedence: None,
            associativity: None,
            production_id: ProductionId(0),
            fields: Default::default(),
        });

    grammar
}

/// Create a simple parse table for arithmetic
/// This is a simplified table - in reality it would be generated by the GLR algorithm
fn create_arithmetic_parse_table() -> ParseTable {
    let mut table = ParseTable {
        state_count: 10,
        symbol_count: 13, // 0-6 terminals, 7-9 skip, 10-12 non-terminals
        action_table: vec![vec![vec![Action::Error]; 13]; 10],
        goto_table: vec![vec![StateId(0); 13]; 10],
        symbol_metadata: vec![],
        symbol_to_index: std::collections::BTreeMap::new(),
        external_scanner_states: vec![],
    };

    // State 0: Initial state
    // Can shift number or (
    table.action_table[0][1] = vec![Action::Shift(StateId(1))]; // number
    table.action_table[0][5] = vec![Action::Shift(StateId(2))]; // (

    // State 1: After number
    // Reduce to factor
    table.action_table[1][0] = vec![Action::Reduce(RuleId(121))]; // EOF
    table.action_table[1][2] = vec![Action::Reduce(RuleId(121))]; // +
    table.action_table[1][3] = vec![Action::Reduce(RuleId(121))]; // -
    table.action_table[1][4] = vec![Action::Reduce(RuleId(121))]; // *
    table.action_table[1][6] = vec![Action::Reduce(RuleId(121))]; // )

    // State 3: After factor
    // Reduce to term
    table.action_table[3][0] = vec![Action::Reduce(RuleId(111))]; // EOF
    table.action_table[3][2] = vec![Action::Reduce(RuleId(111))]; // +
    table.action_table[3][3] = vec![Action::Reduce(RuleId(111))]; // -
    table.action_table[3][4] = vec![Action::Shift(StateId(4))]; // * (shift for term * factor)
    table.action_table[3][6] = vec![Action::Reduce(RuleId(111))]; // )

    // State 5: After term
    // Reduce to expression
    table.action_table[5][0] = vec![Action::Reduce(RuleId(102))]; // EOF
    table.action_table[5][2] = vec![Action::Shift(StateId(6))]; // + (shift for expr + term)
    table.action_table[5][3] = vec![Action::Shift(StateId(7))]; // - (shift for expr - term)
    table.action_table[5][6] = vec![Action::Reduce(RuleId(102))]; // )

    // State 8: After expression (goal state)
    table.action_table[8][0] = vec![Action::Accept]; // EOF - accept!
    table.action_table[8][2] = vec![Action::Shift(StateId(6))]; // +
    table.action_table[8][3] = vec![Action::Shift(StateId(7))]; // -

    // Goto table
    table.goto_table[0][10] = StateId(8); // expression
    table.goto_table[0][11] = StateId(5); // term
    table.goto_table[0][12] = StateId(3); // factor

    // Add symbol metadata
    for i in 0..13 {
        table.symbol_metadata.push(SymbolMetadata {
            name: format!("symbol_{}", i),
            visible: true,
            named: i != 7, // whitespace is unnamed
            supertype: false,
        });
    }

    table
}

/// Test lexing
#[test]
fn test_lexer() {
    let grammar = create_arithmetic_grammar();

    // Create lexer from grammar tokens
    let token_patterns: Vec<_> = grammar
        .tokens
        .iter()
        .map(|(symbol_id, token)| (*symbol_id, token.pattern.clone(), 0))
        .collect();

    let mut lexer = GrammarLexer::new(&token_patterns);
    lexer.set_skip_symbols(vec![SymbolId(7)]); // Skip whitespace

    let input = b"123 + 456";
    let mut tokens = Vec::new();
    let mut pos = 0;

    while pos < input.len() {
        if let Some(token) = lexer.next_token(input, pos) {
            if token.symbol != SymbolId(0) {
                // Not EOF
                tokens.push(token.clone());
            }
            pos = token.end;
        } else {
            break;
        }
    }

    assert_eq!(tokens.len(), 3);
    assert_eq!(tokens[0].symbol, SymbolId(1)); // number
    assert_eq!(tokens[0].text, b"123");
    assert_eq!(tokens[1].symbol, SymbolId(2)); // +
    assert_eq!(tokens[2].symbol, SymbolId(1)); // number
    assert_eq!(tokens[2].text, b"456");
}

/// Test parsing a simple expression
#[test]
fn test_simple_parse() {
    let grammar = create_arithmetic_grammar();
    let parse_table = create_arithmetic_parse_table();
    let mut parser = Parser::new(grammar, parse_table, "test".to_string());

    // Parse the string "123"
    let input = "123";
    let result = parser.parse(input);

    // For now this will fail because our parse table is incomplete
    // but it demonstrates the structure
    match result {
        Ok(node) => {
            println!("Unexpectedly parsed successfully!");
            println!("Root node: symbol={:?}", node.root_kind);
        }
        Err(e) => {
            println!("Parse error (expected): {:?}", e);
        }
    }
}

/// Test the parse node structure
// TODO: Fix this test - ParseNode no longer has terminal/non_terminal constructors
// #[test]
// fn test_parse_node_structure() {
//     // Create a simple parse tree manually
//     let num1 = ParseNode::terminal(SymbolId(1), b"123".to_vec(), 0, 3);
//     let plus = ParseNode::terminal(SymbolId(2), b"+".to_vec(), 4, 5);
//     let num2 = ParseNode::terminal(SymbolId(1), b"456".to_vec(), 6, 9);
//
//     let expr = ParseNode::non_terminal(
//         SymbolId(10), // expression
//         RuleId(100),  // expression -> expression + term
//         vec![num1, plus, num2],
//         0,
//         9,
//     );
//
//     assert_eq!(expr.symbol, SymbolId(10));
//     assert_eq!(expr.children.len(), 3);
//     assert_eq!(expr.start_byte, 0);
//     assert_eq!(expr.end_byte, 9);
// }

/// Test error recovery in lexer
#[test]
fn test_lexer_error_recovery() {
    use rust_sitter::lexer::ErrorRecoveringLexer;

    let grammar = create_arithmetic_grammar();
    let token_patterns: Vec<_> = grammar
        .tokens
        .iter()
        .map(|(symbol_id, token)| (*symbol_id, token.pattern.clone(), 0))
        .collect();

    let base_lexer = GrammarLexer::new(&token_patterns);
    let mut lexer = ErrorRecoveringLexer::new(base_lexer, SymbolId(999)); // Error symbol

    let input = b"123 @ 456"; // @ is not a valid token
    let mut tokens = Vec::new();
    let mut pos = 0;

    while pos < input.len() {
        if let Some(token) = lexer.next_token(input, pos) {
            tokens.push(token.clone());
            pos = token.end;
            if pos >= input.len() {
                break;
            }
        } else {
            break;
        }
    }

    // Should have: number, space, error(@), space, number
    assert!(tokens.iter().any(|t| t.symbol == SymbolId(999))); // Has error token
    assert!(
        tokens
            .iter()
            .any(|t| t.symbol == SymbolId(1) && t.text == b"123")
    );
    assert!(
        tokens
            .iter()
            .any(|t| t.symbol == SymbolId(1) && t.text == b"456")
    );
}
