// Integration tests for the pure-Rust Tree-sitter implementation
use rust_sitter::pure_incremental::Edit;
use rust_sitter::unified_parser::Parser;

#[test]
fn test_complete_workflow() {
    // This test demonstrates the complete workflow of the pure-Rust implementation

    // 1. Create a parser
    let mut parser = Parser::new();

    // 2. Set a language (would normally be generated by rust-sitter-tool)
    // For now, we'll use a mock language
    let language = create_test_language();
    parser
        .set_language(language)
        .expect("Failed to set language");

    // 3. Parse initial source
    let source = "function hello() { return 42; }";
    let result = parser.parse(source, None);

    assert!(
        result.errors.is_empty(),
        "Initial parse had errors: {:?}",
        result.errors
    );
    assert!(result.root.is_some(), "No parse tree produced");

    let tree = rust_sitter::pure_incremental::Tree::new(result.root.unwrap());

    // 4. Make an edit
    let edited_source = "function hello() { return 43; }";
    let edit = Edit {
        start_byte: 26,
        old_end_byte: 28,
        new_end_byte: 28,
        start_point: rust_sitter::pure_parser::Point { row: 0, column: 26 },
        old_end_point: rust_sitter::pure_parser::Point { row: 0, column: 28 },
        new_end_point: rust_sitter::pure_parser::Point { row: 0, column: 28 },
    };

    // 5. Incremental parse
    let incremental_result = parser.parse_with_edits(edited_source, Some(tree), &[edit]);

    assert!(
        incremental_result.errors.is_empty(),
        "Incremental parse had errors"
    );
    assert!(
        incremental_result.root.is_some(),
        "No incremental parse tree"
    );

    // 6. Verify the edit was applied
    let root = incremental_result.root.as_ref().unwrap();
    assert!(
        find_node_with_text(root, edited_source, "43").is_some(),
        "Edit not reflected in tree"
    );
}

#[test]
fn test_error_recovery() {
    let mut parser = Parser::new();
    let language = create_test_language();
    parser
        .set_language(language)
        .expect("Failed to set language");

    // Parse source with syntax errors
    let source = "function hello() { return }"; // Missing value
    let result = parser.parse(source, None);

    // Should still produce a tree, even with errors
    assert!(result.root.is_some(), "No tree produced for error case");
    assert!(
        !result.errors.is_empty(),
        "No errors reported for invalid syntax"
    );

    // Tree should contain ERROR nodes
    let root = result.root.as_ref().unwrap();
    assert!(contains_error_node(root), "No ERROR nodes in tree");
}

#[test]
fn test_cancellation() {
    use std::sync::Arc;
    use std::sync::atomic::{AtomicBool, Ordering};

    let mut parser = Parser::new();
    let language = create_test_language();
    parser
        .set_language(language)
        .expect("Failed to set language");

    // Set up cancellation flag
    let cancel_flag = Arc::new(AtomicBool::new(false));
    parser.set_cancellation_flag(Some(&*cancel_flag));

    // Large source that takes time to parse
    let source = generate_large_source(10000);

    // Set cancellation flag after starting
    let cancel_clone = cancel_flag.clone();
    std::thread::spawn(move || {
        std::thread::sleep(std::time::Duration::from_millis(1));
        cancel_clone.store(true, Ordering::Relaxed);
    });

    let result = parser.parse(&source, None);

    // Parse should be cancelled
    assert!(
        !result.errors.is_empty() || result.root.is_none(),
        "Parse was not cancelled"
    );
}

#[test]
fn test_timeout() {
    let mut parser = Parser::new();
    let language = create_test_language();
    parser
        .set_language(language)
        .expect("Failed to set language");

    // Set a very short timeout
    parser.set_timeout_micros(1); // 1 microsecond

    // Try to parse something that takes longer
    let source = generate_large_source(1000);
    let result = parser.parse(&source, None);

    // Should timeout
    assert!(
        !result.errors.is_empty() || result.root.is_none(),
        "Parse did not timeout"
    );
}

#[test]
fn test_external_scanner_integration() {
    use rust_sitter::pure_external_scanner::{ExternalScanner, ExternalScannerContext};
    use std::sync::{Arc, Mutex};

    // Create a simple external scanner
    #[derive(Default)]
    struct TestScanner {
        count: usize,
    }

    impl ExternalScanner for TestScanner {
        fn scan(&mut self, context: &mut dyn ExternalScannerContext, valid_tokens: &[u16]) -> bool {
            self.count += 1;

            // Simple scanner that accepts any letter as token 1
            if valid_tokens.contains(&1) {
                if let Some(ch) = context.peek() {
                    if ch.is_alphabetic() {
                        context.advance();
                        context.accept_token(1);
                        return true;
                    }
                }
            }
            false
        }

        fn serialize(&self, buffer: &mut Vec<u8>) {
            buffer.extend_from_slice(&self.count.to_le_bytes());
        }

        fn deserialize(&mut self, buffer: &[u8]) {
            if buffer.len() >= 8 {
                self.count = usize::from_le_bytes(buffer[..8].try_into().unwrap());
            }
        }
    }

    let scanner = Arc::new(Mutex::new(TestScanner::default()));

    // Would register scanner with parser here
    // parser.set_external_scanner(scanner);

    // Verify scanner is called during parsing
    assert_eq!(
        scanner.lock().unwrap().count,
        0,
        "Scanner called unexpectedly"
    );
}

// Helper functions
fn create_test_language() -> &'static rust_sitter::pure_parser::TSLanguage {
    static LANGUAGE: rust_sitter::pure_parser::TSLanguage = rust_sitter::pure_parser::TSLanguage {
        version: 14,
        symbol_count: 20,
        alias_count: 0,
        token_count: 10,
        external_token_count: 0,
        state_count: 50,
        large_state_count: 0,
        production_id_count: 1,
        field_count: 0,
        max_alias_sequence_length: 0,
        parse_table: &[],
        small_parse_table: &[],
        small_parse_table_map: &[],
        parse_actions: &[],
        symbol_names: &[],
        field_names: &[],
        field_map_slices: &[],
        field_map_entries: &[],
        symbol_metadata: &[],
        public_symbol_map: &[],
        alias_map: &[],
        alias_sequences: &[],
        lex_modes: &[],
        lex_fn: None,
        keyword_lex_fn: None,
        keyword_capture_token: 0,
        external_scanner: None,
        primary_state_ids: &[],
    };
    &LANGUAGE
}

fn find_node_with_text(
    node: &rust_sitter::pure_parser::ParsedNode,
    source: &str,
    text: &str,
) -> Option<rust_sitter::pure_parser::ParsedNode> {
    let node_text = &source[node.start_byte..node.end_byte];
    if node_text.contains(text) {
        return Some(node.clone());
    }

    for child in &node.children {
        if let Some(found) = find_node_with_text(child, source, text) {
            return Some(found);
        }
    }

    None
}

fn contains_error_node(node: &rust_sitter::pure_parser::ParsedNode) -> bool {
    if node.kind == "ERROR" {
        return true;
    }

    node.children.iter().any(contains_error_node)
}

fn generate_large_source(size: usize) -> String {
    let mut source = String::new();
    for i in 0..size {
        source.push_str(&format!("var x{} = {}; ", i, i));
    }
    source
}
