//! Tests for the parser v3 implementation (legacy, deprecated)
//! These tests are preserved for historical reference but are ignored
//! as the codebase has moved to parser v4 with GLR support.

use rust_sitter::parser::Parser;
use rust_sitter_glr_core::{Action, ParseTable};
use rust_sitter_ir::*;

fn create_simple_arithmetic_grammar() -> Grammar {
    let mut grammar = Grammar {
        name: "arithmetic".to_string(),
        rules: indexmap::IndexMap::new(),
        tokens: indexmap::IndexMap::new(),
        precedences: vec![],
        conflicts: vec![],
        externals: vec![],
        extras: vec![],
        fields: indexmap::IndexMap::new(),
        supertypes: vec![],
        inline_rules: vec![],
        alias_sequences: indexmap::IndexMap::new(),
        production_ids: indexmap::IndexMap::new(),
        rule_names: indexmap::IndexMap::new(),
        max_alias_sequence_length: 0,
        symbol_registry: None,
    };

    // Define symbol IDs
    let _eof_id = SymbolId(0);
    let num_id = SymbolId(1);
    let plus_id = SymbolId(2);
    let expr_id = SymbolId(3);

    // Add tokens
    grammar.tokens.insert(
        num_id,
        Token {
            name: "number".to_string(),
            pattern: TokenPattern::Regex(r"\d+".to_string()),
            fragile: false,
        },
    );

    grammar.tokens.insert(
        plus_id,
        Token {
            name: "plus".to_string(),
            pattern: TokenPattern::String("+".to_string()),
            fragile: false,
        },
    );

    // Add rules
    // Rule 0: expr -> number
    let rule0 = Rule {
        lhs: expr_id,
        rhs: vec![Symbol::Terminal(num_id)],
        precedence: None,
        associativity: None,
        fields: vec![],
        production_id: ProductionId(0),
    };

    // Rule 1: expr -> expr + expr
    let rule1 = Rule {
        lhs: expr_id,
        rhs: vec![
            Symbol::NonTerminal(expr_id),
            Symbol::Terminal(plus_id),
            Symbol::NonTerminal(expr_id),
        ],
        precedence: Some(PrecedenceKind::Static(1)),
        associativity: Some(Associativity::Left),
        fields: vec![],
        production_id: ProductionId(1),
    };

    grammar
        .rules
        .entry(expr_id)
        .or_insert_with(Vec::new)
        .push(rule0);
    grammar
        .rules
        .entry(expr_id)
        .or_insert_with(Vec::new)
        .push(rule1);

    grammar.production_ids.insert(RuleId(0), ProductionId(0));
    grammar.production_ids.insert(RuleId(1), ProductionId(1));

    grammar
}

fn create_simple_parse_table() -> ParseTable {
    // This is a simplified parse table for testing
    // In reality, this would be generated by the GLR table generator

    // State 0: Initial state
    // - number -> shift to state 1
    // - expr -> goto state 2

    // State 1: After seeing number
    // - * -> reduce by rule 0 (expr -> number)

    // State 2: After seeing expr
    // - + -> shift to state 3
    // - EOF -> accept

    // State 3: After seeing expr +
    // - number -> shift to state 4
    // - expr -> goto state 5

    // State 4: After seeing number (in expr + context)
    // - * -> reduce by rule 0 (expr -> number)

    // State 5: After seeing expr + expr
    // - * -> reduce by rule 1 (expr -> expr + expr)

    let mut action_table: Vec<Vec<Vec<Action>>> = vec![vec![vec![Action::Error]; 4]; 6];
    let mut goto_table = vec![vec![StateId(0); 4]; 6];

    // State 0
    action_table[0][1] = vec![Action::Shift(StateId(1))]; // number
    goto_table[0][3] = StateId(2); // expr

    // State 1
    action_table[1][0] = vec![Action::Reduce(RuleId(0))]; // EOF
    action_table[1][1] = vec![Action::Reduce(RuleId(0))]; // number
    action_table[1][2] = vec![Action::Reduce(RuleId(0))]; // +

    // State 2
    action_table[2][0] = vec![Action::Accept]; // EOF
    action_table[2][2] = vec![Action::Shift(StateId(3))]; // +

    // State 3
    action_table[3][1] = vec![Action::Shift(StateId(4))]; // number
    goto_table[3][3] = StateId(5); // expr

    // State 4
    action_table[4][0] = vec![Action::Reduce(RuleId(0))]; // EOF
    action_table[4][1] = vec![Action::Reduce(RuleId(0))]; // number
    action_table[4][2] = vec![Action::Reduce(RuleId(0))]; // +

    // State 5
    action_table[5][0] = vec![Action::Reduce(RuleId(1))]; // EOF
    action_table[5][1] = vec![Action::Reduce(RuleId(1))]; // number
    action_table[5][2] = vec![Action::Reduce(RuleId(1))]; // +

    let mut symbol_to_index = indexmap::IndexMap::new();
    symbol_to_index.insert(SymbolId(0), 0); // EOF
    symbol_to_index.insert(SymbolId(1), 1); // number
    symbol_to_index.insert(SymbolId(2), 2); // +
    symbol_to_index.insert(SymbolId(3), 3); // expr

    ParseTable {
        action_table,
        goto_table,
        symbol_metadata: vec![],
        state_count: 6,
        symbol_count: 4,
        symbol_to_index: symbol_to_index.into_iter().collect(),
        external_scanner_states: Vec::new(),
    }
}

#[test]
#[ignore] // TODO: Update for parser_v4
fn test_parse_number() {
    let grammar = create_simple_arithmetic_grammar();
    let parse_table = create_simple_parse_table();

    let mut parser = Parser::new(grammar, parse_table, "test".to_string());

    match parser.parse("42") {
        Ok(tree) => {
            assert_eq!(tree.root_kind, 3); // expr
            // Tree structure no longer has children field
            // assert_eq!(tree.children.len(), 1);
            // assert_eq!(tree.children[0].symbol, SymbolId(1)); // number
        }
        Err(e) => panic!("Parse failed: {}", e),
    }
}

#[test]
#[ignore] // TODO: Update for parser_v4
fn test_parse_addition() {
    let grammar = create_simple_arithmetic_grammar();
    let parse_table = create_simple_parse_table();

    let mut parser = Parser::new(grammar, parse_table, "test".to_string());

    match parser.parse("1+2") {
        Ok(tree) => {
            assert_eq!(tree.root_kind, 3); // expr
            // Tree structure no longer has children field - skip child assertions
            // assert_eq!(tree.children[0].symbol, SymbolId(3)); // expr (left)
            // assert_eq!(tree.children[1].symbol, SymbolId(2)); // +
            // assert_eq!(tree.children[2].symbol, SymbolId(3)); // expr (right)
        }
        Err(e) => panic!("Parse failed: {}", e),
    }
}

#[test]
#[ignore] // TODO: Update for parser_v4
fn test_parse_with_whitespace() {
    let grammar = create_simple_arithmetic_grammar();
    let parse_table = create_simple_parse_table();

    let mut parser = Parser::new(grammar, parse_table, "test".to_string());

    // The lexer should skip whitespace
    match parser.parse("1 + 2") {
        Ok(tree) => {
            assert_eq!(tree.root_kind, 3); // expr
            // Tree structure no longer has children field - skip child assertions
        }
        Err(e) => panic!("Parse failed: {}", e),
    }
}
