// Comprehensive tests for GLR (Generalized LR) parsing
// These tests verify fork/merge handling for ambiguous grammars

#![cfg(test)]
#![allow(unused_imports, dead_code)]

mod common;

use rust_sitter::error_recovery::{ErrorRecoveryConfig, ErrorRecoveryConfigBuilder};
use rust_sitter::glr_parser::{GLRParser, ParseStack};
use rust_sitter::parser_v4::{Parser, Tree};
use rust_sitter::subtree::Subtree;
use rust_sitter_glr_core::{Action, ParseTable};
use rust_sitter_ir::{
    Grammar, ProductionId, Rule, RuleId, StateId, Symbol, SymbolId, Token, TokenPattern,
};
use std::collections::BTreeMap;
use std::sync::Arc;

// Local symbol constants to avoid magic numbers
const SYM_EOF: SymbolId = SymbolId(0);
const SYM_NUMBER: SymbolId = SymbolId(1);
const SYM_PLUS: SymbolId = SymbolId(2);
const SYM_STAR: SymbolId = SymbolId(3);
const SYM_EXPR: SymbolId = SymbolId(10);

/// Create the classic ambiguous expression grammar
/// E -> E + E | E * E | num
/// This grammar is ambiguous for inputs like "1 + 2 * 3"
fn create_ambiguous_grammar() -> Grammar {
    let mut grammar = Grammar::new("ambiguous_expr".to_string());

    grammar.tokens.insert(
        SYM_NUMBER,
        Token {
            name: "number".to_string(),
            pattern: TokenPattern::Regex(r"\d+".to_string()),
            fragile: false,
        },
    );

    grammar.tokens.insert(
        SYM_PLUS,
        Token {
            name: "plus".to_string(),
            pattern: TokenPattern::String("+".to_string()),
            fragile: false,
        },
    );

    grammar.tokens.insert(
        SYM_STAR,
        Token {
            name: "mult".to_string(),
            pattern: TokenPattern::String("*".to_string()),
            fragile: false,
        },
    );

    // Rules
    // E -> num
    let rule1 = Rule {
        lhs: SYM_EXPR,
        rhs: vec![Symbol::Terminal(SYM_NUMBER)],
        production_id: ProductionId(0),
        precedence: None,
        associativity: None,
        fields: vec![],
    };

    // E -> E + E
    let rule2 = Rule {
        lhs: SYM_EXPR,
        rhs: vec![
            Symbol::NonTerminal(SYM_EXPR),
            Symbol::Terminal(SYM_PLUS),
            Symbol::NonTerminal(SYM_EXPR),
        ],
        production_id: ProductionId(1),
        precedence: None,
        associativity: None,
        fields: vec![],
    };

    // E -> E * E
    let rule3 = Rule {
        lhs: SYM_EXPR,
        rhs: vec![
            Symbol::NonTerminal(SYM_EXPR),
            Symbol::Terminal(SYM_STAR),
            Symbol::NonTerminal(SYM_EXPR),
        ],
        production_id: ProductionId(2),
        precedence: None,
        associativity: None,
        fields: vec![],
    };

    grammar
        .rules
        .entry(SYM_EXPR)
        .or_insert_with(Vec::new)
        .push(rule1);
    grammar
        .rules
        .entry(SYM_EXPR)
        .or_insert_with(Vec::new)
        .push(rule2);
    grammar
        .rules
        .entry(SYM_EXPR)
        .or_insert_with(Vec::new)
        .push(rule3);

    // Add rule names
    grammar
        .rule_names
        .insert(SYM_EXPR, "expression".to_string());

    // Note: Grammar doesn't have a start_rule field in this version
    // The start rule is typically inferred from the rules

    grammar
}

/// Create a parse table with conflicts for testing GLR
fn create_conflicting_parse_table() -> ParseTable {
    // This would normally be generated by the table generator
    // For testing, we create a simple table with shift/reduce conflicts

    let mut action_table = vec![vec![vec![]; 4]; 10]; // Now Vec<Vec<Vec<Action>>>
    let mut goto_table = vec![vec![StateId(0); 1]; 10];

    // State 0: Initial state
    // num -> shift to state 1
    action_table[0][1] = vec![Action::Shift(StateId(1))];

    // State 1: After seeing a number
    // + -> shift to state 2
    // * -> shift to state 3
    // EOF -> reduce by rule 0 (E -> num)
    action_table[1][2] = vec![Action::Shift(StateId(2))];
    action_table[1][3] = vec![Action::Shift(StateId(3))];
    action_table[1][0] = vec![Action::Reduce(RuleId(0))];

    // State 2: After E +
    // num -> shift to state 4
    action_table[2][1] = vec![Action::Shift(StateId(4))];

    // State 3: After E *
    // num -> shift to state 5
    action_table[3][1] = vec![Action::Shift(StateId(5))];

    // State 4: After E + num
    // This is where conflicts occur
    // + -> reduce by rule 1 (E -> E + E)
    // * -> shift to state 6 AND reduce by rule 1 (shift/reduce conflict!)
    // EOF -> reduce by rule 1
    action_table[4][2] = vec![Action::Reduce(RuleId(1))];
    action_table[4][3] = vec![Action::Shift(StateId(6)), Action::Reduce(RuleId(1))]; // Conflict!
    action_table[4][0] = vec![Action::Reduce(RuleId(1))];

    // State 5: After E * num
    // + -> reduce by rule 2 (E -> E * E)
    // * -> reduce by rule 2
    // EOF -> reduce by rule 2
    action_table[5][2] = vec![Action::Reduce(RuleId(2))];
    action_table[5][3] = vec![Action::Reduce(RuleId(2))];
    action_table[5][0] = vec![Action::Reduce(RuleId(2))];

    // State 6: After E + E *
    // num -> shift to state 7
    action_table[6][1] = vec![Action::Shift(StateId(7))];

    // State 7: After E + E * num
    // Everything reduces by rule 2
    action_table[7][2] = vec![Action::Reduce(RuleId(2))];
    action_table[7][3] = vec![Action::Reduce(RuleId(2))];
    action_table[7][0] = vec![Action::Reduce(RuleId(2))];

    // Goto table for expr (symbol 10 -> index 0)
    goto_table[0][0] = StateId(8); // From state 0, expr goes to state 8
    goto_table[2][0] = StateId(4); // From state 2 (after +), expr goes to state 4
    goto_table[3][0] = StateId(5); // From state 3 (after *), expr goes to state 5

    // Accept state
    action_table[8][0] = vec![Action::Accept];

    let mut symbol_to_index = BTreeMap::new();
    symbol_to_index.insert(SYM_EOF, 0); // EOF
    symbol_to_index.insert(SYM_NUMBER, 1); // num
    // Create parse rules for the table
    // These correspond to the grammar rules created in create_ambiguous_grammar
    let rules = vec![
        rust_sitter_glr_core::ParseRule {
            lhs: SYM_EXPR,
            rhs_len: 1, // E -> num
        },
        rust_sitter_glr_core::ParseRule {
            lhs: SYM_EXPR,
            rhs_len: 3, // E -> E + E
        },
        rust_sitter_glr_core::ParseRule {
            lhs: SYM_EXPR,
            rhs_len: 3, // E -> E * E
        },
    ];

    // Build symbol maps
    let mut symbol_to_index: BTreeMap<SymbolId, usize> = BTreeMap::new();
    for i in 0..11 {
        symbol_to_index.insert(SymbolId(i as u16), i);
    }

    let mut nonterminal_to_index: BTreeMap<SymbolId, usize> = BTreeMap::new();
    nonterminal_to_index.insert(SYM_EXPR, SYM_EXPR.0 as usize);

    ParseTable {
        action_table: action_table.clone(),
        goto_table,
        rules,

        // State and symbol counts
        state_count: action_table.len(),
        symbol_count: 11,

        // Symbol bookkeeping
        symbol_to_index,
        index_to_symbol: vec![], // Add missing field
        nonterminal_to_index,
        symbol_metadata: vec![],

        // Token layout / sentinels
        token_count: 9,
        external_token_count: 0,
        eof_symbol: SymbolId(10),
        start_symbol: SYM_EXPR,

        // Parsing config
        initial_state: StateId(0),

        // Lexing config
        lex_modes: vec![
            rust_sitter_glr_core::LexMode {
                lex_state: 0,
                external_lex_state: 0
            };
            action_table.len()
        ],
        extras: vec![],
        external_scanner_states: vec![],

        // Advanced features (unused in tests)
        dynamic_prec_by_rule: vec![],
        rule_assoc_by_rule: vec![],
        alias_sequences: vec![],
        field_names: vec![],
        field_map: BTreeMap::new(),

        // Grammar metadata
        grammar: Grammar::default(),
    }
}

#[test]
fn test_glr_fork_creation() {
    let grammar = create_ambiguous_grammar();
    let parse_table = create_conflicting_parse_table();

    // Create a GLR parser
    let mut parser = GLRParser::new(parse_table, grammar);

    // Process tokens for "1 + 2 * 3"
    parser.process_token(SYM_NUMBER, "1", 0); // num
    parser.process_token(SYM_PLUS, "+", 2); // plus
    parser.process_token(SYM_NUMBER, "2", 4); // num

    // At this point, we should have multiple stacks due to the conflict
    let stack_count_before = parser.stack_count();

    parser.process_token(SYM_STAR, "*", 6); // mult - this should trigger forking

    let stack_count_after = parser.stack_count();

    // We should have more stacks after the conflict
    assert!(
        stack_count_after >= stack_count_before,
        "Expected forking to create additional stacks. Before: {}, After: {}",
        stack_count_before,
        stack_count_after
    );

    parser.process_token(SYM_NUMBER, "3", 8); // num
    parser.process_eof(9);

    // Check that we can get a parse result
    let result = parser.finish();
    assert!(result.is_ok(), "Parse should succeed: {:?}", result);
}

#[test]
fn test_glr_merge() {
    let grammar = create_ambiguous_grammar();
    let parse_table = create_conflicting_parse_table();

    let mut parser = GLRParser::new(parse_table, grammar);

    // Parse an ambiguous expression
    parser.process_token(SYM_NUMBER, "1", 0);
    parser.process_token(SYM_PLUS, "+", 2);
    parser.process_token(SYM_NUMBER, "2", 4);
    parser.process_token(SYM_STAR, "*", 6);
    parser.process_token(SYM_NUMBER, "3", 8);
    parser.process_eof(9);

    // Try to get all alternatives (if feature is available)
    #[cfg(feature = "incremental_glr")]
    {
        let alternatives = parser.finish_all_alternatives();
        assert!(
            alternatives.is_ok(),
            "Should be able to get all parse alternatives"
        );

        let trees = alternatives.unwrap();
        // For a truly ambiguous grammar, we might get multiple parse trees
        // But for now, just verify we get at least one
        assert!(!trees.is_empty(), "Should have at least one parse tree");
    }

    #[cfg(not(feature = "incremental_glr"))]
    {
        // Just finish normally without alternatives
        let result = parser.finish();
        assert!(result.is_ok(), "Should successfully parse");
    }
}

#[test]
fn test_ambiguous_expression_parsing() {
    let grammar = create_ambiguous_grammar();
    let parse_table = create_conflicting_parse_table();

    let mut parser = GLRParser::new(parse_table, grammar);

    // Parse "1 + 2 * 3"
    parser.process_token(SYM_NUMBER, "1", 0);
    parser.process_token(SYM_PLUS, "+", 2);
    parser.process_token(SYM_NUMBER, "2", 4);
    parser.process_token(SYM_STAR, "*", 6);
    parser.process_token(SYM_NUMBER, "3", 8);
    parser.process_eof(9);

    let result = parser.finish();
    assert!(
        result.is_ok(),
        "Should successfully parse ambiguous expression"
    );

    let tree = result.unwrap();
    // The root should be an expression
    assert_eq!(tree.symbol(), SYM_EXPR.0, "Root should be expression");

    // Verify the tree has the expected structure
    // Since this is ambiguous, we just verify it has children
    assert!(tree.children.len() > 0, "Parse tree should have children");
}

#[test]
fn test_glr_error_recovery() {
    let grammar = create_ambiguous_grammar();
    let parse_table = create_conflicting_parse_table();

    let mut parser = GLRParser::new(parse_table, grammar);

    // Enable error recovery with correct field names
    let recovery_config = ErrorRecoveryConfigBuilder::new()
        .max_panic_skip(3)
        .max_consecutive_errors(2)
        .enable_phrase_recovery(true)
        .enable_scope_recovery(false)
        .build();
    parser.enable_error_recovery(recovery_config);

    // Parse with an error: "1 + + 3" (missing number)
    parser.process_token(SYM_NUMBER, "1", 0);
    parser.process_token(SYM_PLUS, "+", 2);
    parser.process_token(SYM_PLUS, "+", 4); // Error: unexpected +
    parser.process_token(SYM_NUMBER, "3", 6);
    parser.process_eof(7);

    // Should still get a result due to error recovery
    let result = parser.finish();
    // May or may not succeed depending on recovery strategy
    // Just verify it doesn't panic
}

#[test]
fn test_glr_expected_symbols() {
    let grammar = create_ambiguous_grammar();
    let parse_table = create_conflicting_parse_table();

    let mut parser = GLRParser::new(parse_table, grammar);

    // After parsing "1 +"
    parser.process_token(SYM_NUMBER, "1", 0);
    parser.process_token(SYM_PLUS, "+", 2);

    // This section uses optional incremental-GLR APIs; keep it discoverable but gated.
    #[cfg(feature = "incremental_glr")]
    {
        let expected = parser.expected_symbols();
        // Should expect a number after +
        assert!(
            expected.contains(&SYM_NUMBER),
            "Should expect number after +"
        );
    }
}

#[test]
fn test_glr_state_management() {
    let grammar = create_ambiguous_grammar();
    let parse_table = create_conflicting_parse_table();

    let mut parser1 = GLRParser::new(parse_table.clone(), grammar.clone());

    // Parse partial input
    parser1.process_token(SYM_NUMBER, "1", 0);
    parser1.process_token(SYM_PLUS, "+", 2);

    // This section uses optional incremental-GLR APIs; keep it discoverable but gated.
    #[cfg(feature = "incremental_glr")]
    {
        // Save state
        let saved_stacks = parser1.get_gss_state();
        let next_id = parser1.get_next_stack_id();

        // Create new parser and restore state
        let mut parser2 = GLRParser::new(parse_table, grammar);
        parser2.set_gss_state(saved_stacks);
        parser2.set_next_stack_id(next_id);

        // Continue parsing
        parser2.process_token(SYM_NUMBER, "2", 4);
        parser2.process_eof(5);

        let result = parser2.finish();
        assert!(
            result.is_ok(),
            "Should successfully parse after state restoration"
        );
    }

    #[cfg(not(feature = "incremental_glr"))]
    {
        // Just continue with the same parser
        parser1.process_token(SYM_NUMBER, "2", 4);
        parser1.process_eof(5);

        let result = parser1.finish();
        assert!(result.is_ok(), "Should successfully parse");
    }
}
