// Test error recovery in the parser
use rust_sitter::parser_v3::{Parser, ParseNode};
use rust_sitter::error_recovery::{ErrorRecoveryConfig, ErrorRecoveryConfigBuilder};
use rust_sitter_ir::*;
use rust_sitter_glr_core::*;
use indexmap::IndexMap;

fn create_test_grammar() -> Grammar {
    let mut grammar = Grammar::new("test".to_string());
    
    // Tokens
    let number = SymbolId(1);
    let plus = SymbolId(2);
    let lparen = SymbolId(3);
    let rparen = SymbolId(4);
    let semicolon = SymbolId(5);
    
    grammar.tokens.insert(number, Token {
        name: "number".to_string(),
        pattern: TokenPattern::Regex(r"\d+".to_string()),
        fragile: false,
    });
    
    grammar.tokens.insert(plus, Token {
        name: "plus".to_string(),
        pattern: TokenPattern::String("+".to_string()),
        fragile: false,
    });
    
    grammar.tokens.insert(lparen, Token {
        name: "lparen".to_string(),
        pattern: TokenPattern::String("(".to_string()),
        fragile: false,
    });
    
    grammar.tokens.insert(rparen, Token {
        name: "rparen".to_string(),
        pattern: TokenPattern::String(")".to_string()),
        fragile: false,
    });
    
    grammar.tokens.insert(semicolon, Token {
        name: "semicolon".to_string(),
        pattern: TokenPattern::String(";".to_string()),
        fragile: false,
    });
    
    // Rules
    let expr = SymbolId(10);
    let stmt = SymbolId(11);
    
    // expr -> number
    grammar.rules.insert(expr, Rule {
        lhs: expr,
        rhs: vec![Symbol::Terminal(number)],
        production_id: ProductionId(0),
        precedence: None,
        associativity: None,
        fields: IndexMap::new(),
        inline: false,
        fragile: false,
        visible: true,
    });
    
    // expr -> expr + expr
    grammar.rules.insert(expr, Rule {
        lhs: expr,
        rhs: vec![
            Symbol::NonTerminal(expr),
            Symbol::Terminal(plus),
            Symbol::NonTerminal(expr),
        ],
        production_id: ProductionId(1),
        precedence: None,
        associativity: None,
        fields: IndexMap::new(),
        inline: false,
        fragile: false,
        visible: true,
    });
    
    // expr -> ( expr )
    grammar.rules.insert(expr, Rule {
        lhs: expr,
        rhs: vec![
            Symbol::Terminal(lparen),
            Symbol::NonTerminal(expr),
            Symbol::Terminal(rparen),
        ],
        production_id: ProductionId(2),
        precedence: None,
        associativity: None,
        fields: IndexMap::new(),
        inline: false,
        fragile: false,
        visible: true,
    });
    
    // stmt -> expr ;
    grammar.rules.insert(stmt, Rule {
        lhs: stmt,
        rhs: vec![
            Symbol::NonTerminal(expr),
            Symbol::Terminal(semicolon),
        ],
        production_id: ProductionId(3),
        precedence: None,
        associativity: None,
        fields: IndexMap::new(),
        inline: false,
        fragile: false,
        visible: true,
    });
    
    grammar
}

fn create_test_parse_table() -> ParseTable {
    // Create a simplified parse table for testing
    // This would normally be generated by the table generator
    ParseTable {
        action_table: vec![vec![Action::Error; 6]; 10],
        goto_table: vec![vec![StateId(0); 2]; 10],
        symbol_metadata: vec![],
        state_count: 10,
        symbol_count: 12,
        symbol_to_index: IndexMap::new(),
    }
}

#[test]
fn test_missing_closing_paren_recovery() {
    let grammar = create_test_grammar();
    let parse_table = create_test_parse_table();
    
    // Configure error recovery
    let error_recovery = ErrorRecoveryConfigBuilder::new()
        .add_sync_token(SymbolId(4)) // rparen
        .add_sync_token(SymbolId(5)) // semicolon
        .add_insertable_token(SymbolId(4)) // can insert rparen
        .enable_scope_recovery(true)
        .build();
    
    let mut parser = Parser::new(grammar, parse_table)
        .with_error_recovery(error_recovery);
    
    // Parse input with missing closing paren: "(1 + 2"
    // With error recovery, it should insert the missing rparen
    let input = "(1 + 2";
    
    match parser.parse(input) {
        Ok(tree) => {
            println!("Parsed with recovery: {:?}", tree);
            // Should have recovered by inserting rparen
        }
        Err(e) => {
            // Without proper parse table, this test might fail
            // but it demonstrates the API
            println!("Parse error: {:?}", e);
        }
    }
}

#[test]
fn test_extra_token_deletion() {
    let grammar = create_test_grammar();
    let parse_table = create_test_parse_table();
    
    // Configure error recovery to delete unexpected tokens
    let error_recovery = ErrorRecoveryConfigBuilder::new()
        .add_deletable_token(SymbolId(2)) // can delete plus
        .build();
    
    let mut parser = Parser::new(grammar, parse_table)
        .with_error_recovery(error_recovery);
    
    // Parse input with extra plus: "1 + + 2"
    // With error recovery, it should delete one plus
    let input = "1 + + 2";
    
    match parser.parse(input) {
        Ok(tree) => {
            println!("Parsed with recovery: {:?}", tree);
        }
        Err(e) => {
            println!("Parse error: {:?}", e);
        }
    }
}

#[test]
fn test_error_node_creation() {
    let grammar = create_test_grammar();
    let parse_table = create_test_parse_table();
    
    // Configure error recovery to create error nodes
    let error_recovery = ErrorRecoveryConfigBuilder::new()
        .enable_error_nodes(true)
        .set_max_recovery_attempts(3)
        .build();
    
    let mut parser = Parser::new(grammar, parse_table)
        .with_error_recovery(error_recovery);
    
    // Parse input with syntax error
    let input = "1 @ 2"; // @ is not a valid token
    
    match parser.parse(input) {
        Ok(tree) => {
            println!("Parsed with error node: {:?}", tree);
            // Should contain an error node
        }
        Err(e) => {
            println!("Parse error: {:?}", e);
        }
    }
}