// Comprehensive benchmarks for pure-Rust Tree-sitter implementation
use criterion::{black_box, criterion_group, criterion_main, Criterion, BenchmarkId};
use rust_sitter::pure_parser::{Parser, TSLanguage};
use rust_sitter::unified_parser::Parser as UnifiedParser;
use rust_sitter::pure_incremental::{Edit, Tree};

// Create test languages of various complexities
fn create_simple_language() -> &'static TSLanguage {
    // This would be generated by rust-sitter-tool
    static LANGUAGE: TSLanguage = TSLanguage {
        version: 14,
        symbol_count: 10,
        alias_count: 0,
        token_count: 5,
        external_token_count: 0,
        state_count: 20,
        large_state_count: 0,
        production_id_count: 1,
        field_count: 0,
        max_alias_sequence_length: 0,
        parse_table: &[],
        small_parse_table: &[],
        small_parse_table_map: &[],
        parse_actions: &[],
        symbol_names: &[],
        field_names: &[],
        field_map_slices: &[],
        field_map_entries: &[],
        symbol_metadata: &[],
        public_symbol_map: &[],
        alias_map: &[],
        alias_sequences: &[],
        lex_modes: &[],
        lex_fn: None,
        keyword_lex_fn: None,
        keyword_capture_token: 0,
        external_scanner: None,
        primary_state_ids: &[],
    };
    &LANGUAGE
}

// Generate test source code of various sizes
fn generate_arithmetic_expr(depth: usize) -> String {
    if depth == 0 {
        "42".to_string()
    } else {
        format!("({} + {} * {})", 
            generate_arithmetic_expr(depth - 1),
            depth,
            generate_arithmetic_expr(depth - 1))
    }
}

fn generate_json(size: usize) -> String {
    let mut result = String::from("{");
    for i in 0..size {
        if i > 0 {
            result.push(',');
        }
        result.push_str(&format!(r#""key{}": {}"#, i, if i % 2 == 0 { 
            format!(r#""value{}""#, i)
        } else {
            format!("{}", i)
        }));
    }
    result.push('}');
    result
}

// Benchmark basic parsing
fn bench_basic_parsing(c: &mut Criterion) {
    let mut group = c.benchmark_group("basic_parsing");
    let language = create_simple_language();
    
    for size in [10, 100, 1000, 10000] {
        let source = generate_arithmetic_expr((size as f64).log2() as usize);
        
        group.bench_with_input(
            BenchmarkId::new("parse", size),
            &source,
            |b, source| {
                let mut parser = Parser::new();
                parser.set_language(language).unwrap();
                b.iter(|| {
                    let result = parser.parse_string(black_box(source));
                    black_box(result);
                });
            },
        );
    }
    
    group.finish();
}

// Benchmark incremental parsing
fn bench_incremental_parsing(c: &mut Criterion) {
    let mut group = c.benchmark_group("incremental_parsing");
    let language = create_simple_language();
    
    for size in [100, 1000, 10000] {
        let mut source = generate_json(size);
        let edit_pos = source.len() / 2;
        
        // Parse initial tree
        let mut parser = UnifiedParser::new();
        parser.set_language(language).unwrap();
        let initial_result = parser.parse(&source, None);
        
        if let Some(tree) = initial_result.root {
            // Make a small edit
            source.replace_range(edit_pos..edit_pos+5, "\"new\"");
            
            let edit = Edit {
                start_byte: edit_pos,
                old_end_byte: edit_pos + 5,
                new_end_byte: edit_pos + 5,
                start_point: rust_sitter::pure_parser::Point { row: 0, column: edit_pos },
                old_end_point: rust_sitter::pure_parser::Point { row: 0, column: edit_pos + 5 },
                new_end_point: rust_sitter::pure_parser::Point { row: 0, column: edit_pos + 5 },
            };
            
            group.bench_with_input(
                BenchmarkId::new("incremental", size),
                &(&source, &edit),
                |b, (source, edit)| {
                    b.iter(|| {
                        let result = parser.parse_with_edits(
                            black_box(source),
                            Some(Tree::new(tree.clone())),
                            &[edit.clone()]
                        );
                        black_box(result);
                    });
                },
            );
        }
    }
    
    group.finish();
}

// Benchmark lexer performance
fn bench_lexer(c: &mut Criterion) {
    let mut group = c.benchmark_group("lexer");
    
    // Test different token patterns
    let patterns = vec![
        ("identifiers", "foo bar baz qux quux corge grault garply".repeat(100)),
        ("numbers", "123 456 789 3.14 2.718 1.414".repeat(100)),
        ("strings", r#""hello" "world" "rust" "sitter" "parser""#.repeat(100)),
        ("mixed", r#"fn main() { let x = 42; println!("{}", x); }"#.repeat(50)),
    ];
    
    for (name, source) in patterns {
        group.bench_with_input(
            BenchmarkId::new("tokenize", name),
            &source,
            |b, source| {
                let language = create_simple_language();
                let mut parser = Parser::new();
                parser.set_language(language).unwrap();
                
                b.iter(|| {
                    // The lexer runs as part of parsing
                    let result = parser.parse_string(black_box(source));
                    black_box(result);
                });
            },
        );
    }
    
    group.finish();
}

// Benchmark memory usage patterns
fn bench_memory_patterns(c: &mut Criterion) {
    let mut group = c.benchmark_group("memory");
    
    // Test parsing with different memory patterns
    let language = create_simple_language();
    
    // Deep nesting (stress tests stack)
    let deep_expr = (0..100).fold("1".to_string(), |acc, _| format!("({} + 1)", acc));
    
    group.bench_function("deep_nesting", |b| {
        let mut parser = Parser::new();
        parser.set_language(language).unwrap();
        
        b.iter(|| {
            let result = parser.parse_string(black_box(&deep_expr));
            black_box(result);
        });
    });
    
    // Wide tree (stress tests heap)
    let wide_expr = (0..1000).map(|i| i.to_string()).collect::<Vec<_>>().join(" + ");
    
    group.bench_function("wide_tree", |b| {
        let mut parser = Parser::new();
        parser.set_language(language).unwrap();
        
        b.iter(|| {
            let result = parser.parse_string(black_box(&wide_expr));
            black_box(result);
        });
    });
    
    group.finish();
}

// Benchmark parallel parsing
#[cfg(feature = "parallel")]
fn bench_parallel_parsing(c: &mut Criterion) {
    use rayon::prelude::*;
    
    let mut group = c.benchmark_group("parallel");
    let language = create_simple_language();
    
    // Generate multiple documents
    let documents: Vec<String> = (0..100)
        .map(|i| generate_json(100 + i))
        .collect();
    
    group.bench_function("sequential", |b| {
        b.iter(|| {
            let results: Vec<_> = documents.iter()
                .map(|doc| {
                    let mut parser = Parser::new();
                    parser.set_language(language).unwrap();
                    parser.parse_string(black_box(doc))
                })
                .collect();
            black_box(results);
        });
    });
    
    group.bench_function("parallel", |b| {
        b.iter(|| {
            let results: Vec<_> = documents.par_iter()
                .map(|doc| {
                    let mut parser = Parser::new();
                    parser.set_language(language).unwrap();
                    parser.parse_string(black_box(doc))
                })
                .collect();
            black_box(results);
        });
    });
    
    group.finish();
}

// Benchmark against tree-sitter C implementation if available
#[cfg(feature = "tree-sitter-standard")]
fn bench_vs_c_implementation(c: &mut Criterion) {
    use tree_sitter as ts;
    
    let mut group = c.benchmark_group("rust_vs_c");
    
    // Use a real grammar if available
    let source = r#"
        function fibonacci(n) {
            if (n <= 1) return n;
            return fibonacci(n - 1) + fibonacci(n - 2);
        }
        
        const result = fibonacci(10);
        console.log("Result:", result);
    "#.repeat(10);
    
    // Benchmark Rust implementation
    group.bench_function("rust_impl", |b| {
        let language = create_simple_language();
        let mut parser = Parser::new();
        parser.set_language(language).unwrap();
        
        b.iter(|| {
            let result = parser.parse_string(black_box(&source));
            black_box(result);
        });
    });
    
    // Benchmark C implementation
    group.bench_function("c_impl", |b| {
        let mut parser = ts::Parser::new();
        // Would need to set actual language here
        
        b.iter(|| {
            let tree = parser.parse(black_box(&source), None);
            black_box(tree);
        });
    });
    
    group.finish();
}

criterion_group!(
    benches,
    bench_basic_parsing,
    bench_incremental_parsing,
    bench_lexer,
    bench_memory_patterns,
);

#[cfg(feature = "parallel")]
criterion_group!(parallel_benches, bench_parallel_parsing);

#[cfg(feature = "tree-sitter-standard")]
criterion_group!(comparison_benches, bench_vs_c_implementation);

#[cfg(all(not(feature = "parallel"), not(feature = "tree-sitter-standard")))]
criterion_main!(benches);

#[cfg(all(feature = "parallel", not(feature = "tree-sitter-standard")))]
criterion_main!(benches, parallel_benches);

#[cfg(all(not(feature = "parallel"), feature = "tree-sitter-standard"))]
criterion_main!(benches, comparison_benches);

#[cfg(all(feature = "parallel", feature = "tree-sitter-standard"))]
criterion_main!(benches, parallel_benches, comparison_benches);