#!/usr/bin/env bash
# Test Inventory Generator
# Automatically counts and categorizes tests across the workspace

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Output file
OUTPUT="${REPO_ROOT}/TEST_INVENTORY_REPORT.md"

echo "# Test Inventory Report" > "$OUTPUT"
echo "**Generated**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Function to count tests in a crate
count_tests() {
    local crate_path=$1
    local crate_name=$2

    echo -e "${BLUE}Analyzing ${crate_name}...${NC}"

    # Count total tests
    local total_tests=$(cd "$crate_path" && cargo test --lib --tests 2>/dev/null -- --list 2>/dev/null | grep -c "test " || echo "0")

    # Count ignored tests
    local ignored_tests=$(find "$crate_path" -name "*.rs" -type f -exec grep -l "#\[ignore" {} \; | wc -l)

    # Count test files
    local test_files=$(find "$crate_path/tests" -name "*.rs" -type f 2>/dev/null | wc -l || echo "0")

    # Count inline unit tests
    local unit_test_count=$(find "$crate_path/src" -name "*.rs" -type f -exec grep -c "#\[test\]" {} \; 2>/dev/null | awk '{s+=$1} END {print s}' || echo "0")

    echo "## $crate_name" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    echo "- **Total Tests**: $total_tests" >> "$OUTPUT"
    echo "- **Ignored Tests**: $ignored_tests" >> "$OUTPUT"
    echo "- **Test Files**: $test_files" >> "$OUTPUT"
    echo "- **Unit Tests**: $unit_test_count" >> "$OUTPUT"
    echo "" >> "$OUTPUT"

    # List ignored tests with reasons
    if [ "$ignored_tests" -gt 0 ]; then
        echo "### Ignored Tests" >> "$OUTPUT"
        echo "" >> "$OUTPUT"
        echo '```' >> "$OUTPUT"
        find "$crate_path" -name "*.rs" -type f -exec grep -B2 "#\[ignore" {} \; | grep -E "(fn test_|#\[ignore)" >> "$OUTPUT" || true
        echo '```' >> "$OUTPUT"
        echo "" >> "$OUTPUT"
    fi
}

# Count tests for each major crate
echo -e "${GREEN}=== Generating Test Inventory ===${NC}"

# Core crates
count_tests "$REPO_ROOT/runtime" "adze (runtime)"
count_tests "$REPO_ROOT/macro" "adze-macro"
count_tests "$REPO_ROOT/glr-core" "adze-glr-core"
count_tests "$REPO_ROOT/tablegen" "adze-tablegen"
count_tests "$REPO_ROOT/tool" "adze-tool"
count_tests "$REPO_ROOT/ir" "adze-ir"
count_tests "$REPO_ROOT/common" "adze-common"

# Example crates
count_tests "$REPO_ROOT/example" "example"

# Summary
echo "## Summary" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Calculate totals
total_all_tests=0
total_ignored=0

for crate in runtime macro glr-core tablegen tool ir common example; do
    if [ -d "$REPO_ROOT/$crate" ]; then
        crate_tests=$(cd "$REPO_ROOT/$crate" && cargo test --lib --tests 2>/dev/null -- --list 2>/dev/null | grep -c "test " || echo "0")
        total_all_tests=$((total_all_tests + crate_tests))

        crate_ignored=$(find "$REPO_ROOT/$crate" -name "*.rs" -type f -exec grep -l "#\[ignore" {} \; | wc -l)
        total_ignored=$((total_ignored + crate_ignored))
    fi
done

echo "- **Total Tests Across Workspace**: $total_all_tests" >> "$OUTPUT"
echo "- **Total Ignored Tests**: $total_ignored" >> "$OUTPUT"
echo "- **Passing Tests**: $((total_all_tests - total_ignored))" >> "$OUTPUT"
echo "- **Pass Rate**: $(awk "BEGIN {printf \"%.1f\", (($total_all_tests - $total_ignored) / $total_all_tests * 100)}")%" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Policy Compliance Check
echo "## Policy Compliance" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Define minimum test counts (from TEST_INVENTORY.md)
declare -A min_counts=(
    ["runtime"]=50
    ["macro"]=13
    ["glr-core"]=30
    ["tablegen"]=8
    ["tool"]=10
)

compliant=true

for crate in "${!min_counts[@]}"; do
    if [ -d "$REPO_ROOT/$crate" ]; then
        actual=$(cd "$REPO_ROOT/$crate" && cargo test --lib --tests 2>/dev/null -- --list 2>/dev/null | grep -c "test " || echo "0")
        required=${min_counts[$crate]}

        if [ "$actual" -ge "$required" ]; then
            status="✅ PASS"
        else
            status="❌ FAIL"
            compliant=false
        fi

        echo "- **$crate**: $actual / $required required - $status" >> "$OUTPUT"
    fi
done

echo "" >> "$OUTPUT"

if $compliant; then
    echo "**Status**: ✅ All crates meet minimum test requirements" >> "$OUTPUT"
    echo -e "${GREEN}✅ All crates meet minimum test requirements${NC}"
else
    echo "**Status**: ❌ Some crates below minimum test requirements" >> "$OUTPUT"
    echo -e "${RED}❌ Some crates below minimum test requirements${NC}"
fi

echo "" >> "$OUTPUT"
echo "---" >> "$OUTPUT"
echo "*Generated by scripts/test-inventory.sh*" >> "$OUTPUT"

echo -e "${GREEN}Report written to: $OUTPUT${NC}"
cat "$OUTPUT"
