// Demo of external scanner integration with pure-Rust parser
use rust_sitter::pure_external_scanner::{ExternalScanner, ExternalScannerRegistry};
use rust_sitter::pure_parser::{Parser, TSLanguage};
use std::sync::Arc;

/// Example: Python-style string scanner that handles triple-quoted strings
struct PythonStringScanner {
    quote_count: usize,
    quote_char: Option<char>,
}

impl PythonStringScanner {
    fn new() -> Self {
        Self {
            quote_count: 0,
            quote_char: None,
        }
    }
}

impl ExternalScanner for PythonStringScanner {
    fn scan(&mut self, _lexer: &mut dyn rust_sitter::pure_external_scanner::Lexer, valid_symbols: &[bool]) -> bool {
        // Check if we should look for string tokens
        const STRING_TOKEN: usize = 0;
        const TRIPLE_STRING_TOKEN: usize = 1;
        
        if valid_symbols.len() <= TRIPLE_STRING_TOKEN || (!valid_symbols[STRING_TOKEN] && !valid_symbols[TRIPLE_STRING_TOKEN]) {
            return false;
        }
        
        // For demo purposes, we'll just return false
        // In a real implementation, we would use the lexer interface
        false
    }
    
    fn serialize(&self, buffer: &mut [u8]) -> usize {
        if buffer.len() >= 2 {
            buffer[0] = self.quote_count as u8;
            buffer[1] = self.quote_char.map(|c| c as u8).unwrap_or(0);
            2
        } else {
            0
        }
    }
    
    fn deserialize(&mut self, buffer: &[u8]) {
        if buffer.len() >= 2 {
            self.quote_count = buffer[0] as usize;
            self.quote_char = if buffer[1] != 0 {
                Some(buffer[1] as char)
            } else {
                None
            };
        }
    }
}

/// Create a simple language with external scanner
fn create_string_language() -> &'static TSLanguage {
    // This would normally be generated by rust-sitter-tool
    // For demo purposes, we'll create a minimal language structure
    static LANGUAGE: TSLanguage = TSLanguage {
        version: 14,
        symbol_count: 10,
        alias_count: 0,
        token_count: 5,
        external_token_count: 2,
        state_count: 20,
        large_state_count: 0,
        production_id_count: 1,
        field_count: 0,
        max_alias_sequence_length: 0,
        parse_table: &[],
        small_parse_table: &[],
        small_parse_table_map: &[],
        parse_actions: &[],
        symbol_names: &[],
        field_names: &[],
        field_map_slices: &[],
        field_map_entries: &[],
        symbol_metadata: &[],
        public_symbol_map: &[],
        alias_map: &[],
        alias_sequences: &[],
        lex_modes: &[],
        lex_fn: None,
        keyword_lex_fn: None,
        keyword_capture_token: 0,
        external_scanner: None,
        primary_state_ids: &[],
    };
    
    &LANGUAGE
}

fn main() {
    // Create scanner registry and register our scanner
    let mut registry = ExternalScannerRegistry::new();
    let scanner = Arc::new(Box::new(PythonStringScanner::new()) as Box<dyn ExternalScanner>);
    registry.register("python_strings", scanner);
    
    // Create parser with external scanner support
    let mut parser = Parser::new();
    let language = create_string_language();
    parser.set_language(language).unwrap();
    
    // Test parsing various string formats
    let test_cases = vec![
        r#"'hello world'"#,
        r#""hello world""#,
        r#"'''triple quoted string'''"#,
        r#""""another triple quoted string""""#,
        r#"'escaped \' quote'"#,
        r#""string with \n newline""#,
    ];
    
    for test in test_cases {
        println!("Parsing: {}", test);
        let result = parser.parse_string(test);
        match result.root {
            Some(root) => println!("  ✓ Parsed successfully: {:?}", root),
            None => println!("  ✗ Parse failed with {} errors", result.errors.len()),
        }
    }
    
    // Demonstrate serialization/deserialization
    let mut scanner = PythonStringScanner::new();
    scanner.quote_count = 3;
    scanner.quote_char = Some('"');
    
    let mut buffer = vec![0u8; 10];
    let len = scanner.serialize(&mut buffer);
    println!("\nSerialized scanner state: {:?}", &buffer[..len]);
    
    let mut restored_scanner = PythonStringScanner::new();
    restored_scanner.deserialize(&buffer);
    println!("Restored quote_count: {}", restored_scanner.quote_count);
    println!("Restored quote_char: {:?}", restored_scanner.quote_char);
}